import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { CaseRecord } from './types';

export const generatePDFReport = async (caseRecord: CaseRecord) => {
  const doc = new jsPDF();
  const { patientDetails, diagnosis } = caseRecord;

  // Header Background
  doc.setFillColor(37, 99, 235); // medical blue
  doc.rect(0, 0, 210, 40, 'F');

  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.text('o_Dtect Clinical Analysis Report', 14, 20);

  doc.setFontSize(10);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 30);
  doc.text(`Session ID: ${caseRecord.id.slice(0, 8).toUpperCase()}`, 150, 30);

  // Patient Info
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.text('Patient Demographics', 14, 55);

  autoTable(doc, {
    startY: 60,
    head: [['Patient Name', 'Patient ID', 'Age / Gender', 'Exam Date']],
    body: [[
      patientDetails.patientName || 'N/A',
      patientDetails.patientId || 'N/A',
      `${patientDetails.age || '-'} / ${patientDetails.gender || '-'}`,
      patientDetails.examinationDate || new Date().toLocaleDateString()
    ]],
    theme: 'plain',
    styles: { fontSize: 10, cellPadding: 2 },
    headStyles: { fillColor: [240, 240, 240], textColor: 50, fontStyle: 'bold' }
  });

  // Clinical Assessment Summary (New)
  doc.setFontSize(14);
  doc.text('Clinical Assessment Assessment', 14, 90);

  autoTable(doc, {
    startY: 95,
    head: [['Primary Diagnosis', 'Confidence', 'Stage', 'Risk Stratification', 'Urgency']],
    body: [[
      diagnosis.predictedClass,
      `${diagnosis.confidence}%`,
      diagnosis.stage || '-',
      diagnosis.riskLevel || '-',
      diagnosis.urgency || '-'
    ]],
    theme: 'grid',
    styles: { fontSize: 11, cellPadding: 5, halign: 'center' },
    headStyles: { fillColor: [37, 99, 235], textColor: 255, fontStyle: 'bold' },
    columnStyles: {
      0: { fontStyle: 'bold' },
      3: { textColor: diagnosis.riskLevel === 'High' ? [220, 38, 38] : [0, 0, 0] }, // Highlight High Risk
      4: { textColor: diagnosis.urgency === 'Immediate' ? [220, 38, 38] : [0, 0, 0] }
    }
  });

  // Clinical Action Plan (New)
  let currentY = (doc as any).lastAutoTable.finalY + 15;
  doc.setFontSize(14);
  doc.text('Recommended Action Plan', 14, currentY);

  const stepsData = (diagnosis.nextSteps || ['Review clinically']).map(step => [step]);

  autoTable(doc, {
    startY: currentY + 5,
    body: stepsData,
    theme: 'striped',
    styles: { fontSize: 10, cellPadding: 3 },
    alternateRowStyles: { fillColor: [248, 250, 252] }
  });

  // AI Interpretation
  currentY = (doc as any).lastAutoTable.finalY + 15;
  doc.setFontSize(14);
  doc.text('AI Interpretation', 14, currentY);

  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  const splitText = doc.splitTextToSize(diagnosis.explanation, 180);
  doc.text(splitText, 14, currentY + 7);

  // Differential Diagnosis (New)
  if (diagnosis.differentialDiagnosis && diagnosis.differentialDiagnosis.length > 0) {
    currentY += splitText.length * 5 + 15;
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text('Differential Diagnosis Hints', 14, currentY);

    const diffData = diagnosis.differentialDiagnosis.map(d => [d.condition, `${(d.probability * 100).toFixed(1)}% Match`]);
    autoTable(doc, {
      startY: currentY + 5,
      head: [['Condition', 'Similarity Match']],
      body: diffData,
      theme: 'grid',
      styles: { fontSize: 9 },
      headStyles: { fillColor: [100, 116, 139] }
    });
  }

  // Footer Disclaimer
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('DISCLAIMER: This report is generated by an AI screening tool and DOES NOT constitute a final medical diagnosis. All results must be verified by a qualified healthcare professional.', 105, pageHeight - 10, { align: 'center' });

  // Save the PDF
  doc.save(`ODtect_Report_${caseRecord.id.slice(0, 6)}.pdf`);
};
